services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - expenses_tracker_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  expenses_tracker_data: